name: Dhaf Release

on:
  push:
    tags:
      - 'v*.*.[0-9]+'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest

    steps:
    - name: download linux-x64 artifacts
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: linux-x64.yml
        workflow_conclusion: success
        path: linux-x64

    - name: download win-x64 artifacts
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: win-x64.yml
        workflow_conclusion: success
        path: win-x64

    - name: download osx-x64 artifacts
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: osx-x64.yml
        workflow_conclusion: success
        path: osx-x64

    - name: set the release version from tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: zip linux-x64 artifacts
      uses: papeloto/action-zip@v1
      with:
        files: linux-x64
        recursive: true
        dest: dhaf-${{ env.RELEASE_VERSION }}-linux-x64.zip

    - name: zip win-x64 artifacts
      uses: papeloto/action-zip@v1
      with:
        files: win-x64
        recursive: true
        dest: dhaf-${{ env.RELEASE_VERSION }}-win-x64.zip

    - name: zip osx-x64 artifacts
      uses: papeloto/action-zip@v1
      with:
        files: osx-x64
        recursive: true
        dest: dhaf-${{ env.RELEASE_VERSION }}-osx-x64.zip

    - name: release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dhaf-${{ env.RELEASE_VERSION }}-linux-x64.zip
          dhaf-${{ env.RELEASE_VERSION }}-win-x64.zip
          dhaf-${{ env.RELEASE_VERSION }}-osx-x64.zip
