name: macOS-x64

on:
  push:
    tags:
      - 'v*.*.*-osx-x64'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup .net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: restore dependencies
      run: dotnet restore src/Dhaf.sln

    # TODO: `--no-dependencies` using (this is difficult because extensions have their own directory, and they cannot detect the root `refs` directory)

    - name: build core
      run: dotnet publish src/Dhaf.Core/Dhaf.Core.csproj  --configuration Release --no-restore -nowarn:CS1998 -r osx-x64 -o bin/osx-x64/core /p:DebugType=None /p:DebugSymbols=false

    - name: build dhaf.node
      run: dotnet publish src/Dhaf.Node/Dhaf.Node.csproj --configuration Release --no-dependencies --no-restore -nowarn:CS1998 -r osx-x64 -o bin/osx-x64 -p:PublishSingleFile=true --self-contained false /p:DebugType=None /p:DebugSymbols=false

    - name: build dhaf.cli
      run: dotnet publish src/Dhaf.CLI/Dhaf.CLI.csproj --configuration Release --no-dependencies --no-restore -nowarn:CS1998 -r osx-x64 -o bin/osx-x64 -p:PublishSingleFile=true --self-contained false /p:DebugType=None /p:DebugSymbols=false

    - name: build core extensions
      run: |
        dotnet publish src/Dhaf.HealthCheckers.Web/Dhaf.HealthCheckers.Web.csproj --configuration Release --no-restore -nowarn:CS1998 -r osx-x64 -o bin/osx-x64/ext/hc/web /p:DebugType=None /p:DebugSymbols=false
        dotnet publish src/Dhaf.HealthCheckers.Exec/Dhaf.HealthCheckers.Exec.csproj --configuration Release --no-restore -nowarn:CS1998 -r osx-x64 -o bin/osx-x64/ext/hc/exec /p:DebugType=None /p:DebugSymbols=false
        
        dotnet publish src/Dhaf.Switchers.Cloudflare/Dhaf.Switchers.Cloudflare.csproj --configuration Release --no-restore -nowarn:CS1998 -r osx-x64 -o bin/osx-x64/ext/sw/cloudflare /p:DebugType=None /p:DebugSymbols=false
        dotnet publish src/Dhaf.Switchers.Exec/Dhaf.Switchers.Exec.csproj --configuration Release --no-restore -nowarn:CS1998 -r osx-x64 -o bin/osx-x64/ext/sw/exec /p:DebugType=None /p:DebugSymbols=false
        
        dotnet publish src/Dhaf.Notifiers.Email/Dhaf.Notifiers.Email.csproj --configuration Release --no-restore -nowarn:CS1998 -r osx-x64 -o bin/osx-x64/ext/ntf/email /p:DebugType=None /p:DebugSymbols=false
        dotnet publish src/Dhaf.Notifiers.Telegram/Dhaf.Notifiers.Telegram.csproj --configuration Release --no-restore -nowarn:CS1998 -r osx-x64 -o bin/osx-x64/ext/ntf/tg /p:DebugType=None /p:DebugSymbols=false

    - name: prepare artifacts
      run: |
        mkdir -p osx-x64-artifacts
        mkdir -p osx-x64-artifacts/libs
        mkdir -p osx-x64-artifacts/extensions/health-checkers/web
        mkdir -p osx-x64-artifacts/extensions/health-checkers/exec
        mkdir -p osx-x64-artifacts/extensions/switchers/cloudflare
        mkdir -p osx-x64-artifacts/extensions/switchers/exec
        mkdir -p osx-x64-artifacts/extensions/notifiers/email
        mkdir -p osx-x64-artifacts/extensions/notifiers/tg

        mv ./bin/osx-x64/Dhaf.Node osx-x64-artifacts/dhaf.node
        mv ./bin/osx-x64/Dhaf.CLI osx-x64-artifacts/dhaf.cli
        mv ./bin/osx-x64/appsettings.json ./bin/osx-x64/nlog.config osx-x64-artifacts
        mv ./bin/osx-x64/core/* osx-x64-artifacts/libs

        mv ./bin/osx-x64/ext/hc/web/* osx-x64-artifacts/extensions/health-checkers/web
        mv ./bin/osx-x64/ext/hc/exec/* osx-x64-artifacts/extensions/health-checkers/exec
        mv ./bin/osx-x64/ext/sw/cloudflare/* osx-x64-artifacts/extensions/switchers/cloudflare
        mv ./bin/osx-x64/ext/sw/exec/* osx-x64-artifacts/extensions/switchers/exec
        mv ./bin/osx-x64/ext/ntf/email/* osx-x64-artifacts/extensions/notifiers/email
        mv ./bin/osx-x64/ext/ntf/tg/* osx-x64-artifacts/extensions/notifiers/tg

    - name: upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: osx-x64-artifacts
        path: osx-x64-artifacts

    - name: set the release version from tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: zip artifacts
      uses: papeloto/action-zip@v1
      with:
        files: osx-x64-artifacts
        recursive: true
        dest: dhaf-${{ env.RELEASE_VERSION }}.zip

    - name: release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags')
      with:
        files: dhaf-${{ env.RELEASE_VERSION }}.zip
