name: Windows-x64

on:
  push:
    tags:
      - 'v*.*.*-win-x64'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup .net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x

    - name: restore dependencies
      run: dotnet restore src/Dhaf.sln

    # TODO: `--no-dependencies` using (this is difficult because extensions have their own directory, and they cannot detect the root `refs` directory)

    - name: build core
      run: dotnet publish src/Dhaf.Core/Dhaf.Core.csproj  --configuration Release --no-restore -nowarn:CS1998 -r win-x64 -o bin/win-x64/core /p:DebugType=None /p:DebugSymbols=false

    - name: build dhaf.node
      run: dotnet publish src/Dhaf.Node/Dhaf.Node.csproj --configuration Release --no-dependencies --no-restore -nowarn:CS1998 -r win-x64 -o bin/win-x64 -p:PublishSingleFile=true --self-contained false /p:DebugType=None /p:DebugSymbols=false

    - name: build dhaf.cli
      run: dotnet publish src/Dhaf.CLI/Dhaf.CLI.csproj --configuration Release --no-dependencies --no-restore -nowarn:CS1998 -r win-x64 -o bin/win-x64 -p:PublishSingleFile=true --self-contained false /p:DebugType=None /p:DebugSymbols=false

    - name: build core extensions
      run: |
        dotnet publish src/Dhaf.HealthCheckers.Web/Dhaf.HealthCheckers.Web.csproj --configuration Release --no-restore -nowarn:CS1998 -r win-x64 -o bin/win-x64/ext/hc/web /p:DebugType=None /p:DebugSymbols=false
        dotnet publish src/Dhaf.HealthCheckers.Exec/Dhaf.HealthCheckers.Exec.csproj --configuration Release --no-restore -nowarn:CS1998 -r win-x64 -o bin/win-x64/ext/hc/exec /p:DebugType=None /p:DebugSymbols=false
        dotnet publish src/Dhaf.HealthCheckers.Tcp/Dhaf.HealthCheckers.Tcp.csproj --configuration Release --no-restore -nowarn:CS1998 -r win-x64 -o bin/win-x64/ext/hc/tcp /p:DebugType=None /p:DebugSymbols=false
        
        dotnet publish src/Dhaf.Switchers.Cloudflare/Dhaf.Switchers.Cloudflare.csproj --configuration Release --no-restore -nowarn:CS1998 -r win-x64 -o bin/win-x64/ext/sw/cloudflare /p:DebugType=None /p:DebugSymbols=false
        dotnet publish src/Dhaf.Switchers.GoogleCloud/Dhaf.Switchers.GoogleCloud.csproj --configuration Release --no-restore -nowarn:CS1998 -r win-x64 -o bin/win-x64/ext/sw/google-cloud /p:DebugType=None /p:DebugSymbols=false
        dotnet publish src/Dhaf.Switchers.Exec/Dhaf.Switchers.Exec.csproj --configuration Release --no-restore -nowarn:CS1998 -r win-x64 -o bin/win-x64/ext/sw/exec /p:DebugType=None /p:DebugSymbols=false
        
        dotnet publish src/Dhaf.Notifiers.Email/Dhaf.Notifiers.Email.csproj --configuration Release --no-restore -nowarn:CS1998 -r win-x64 -o bin/win-x64/ext/ntf/email /p:DebugType=None /p:DebugSymbols=false
        dotnet publish src/Dhaf.Notifiers.Telegram/Dhaf.Notifiers.Telegram.csproj --configuration Release --no-restore -nowarn:CS1998 -r win-x64 -o bin/win-x64/ext/ntf/tg /p:DebugType=None /p:DebugSymbols=false

    - name: set the release version from tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: prepare artifacts
      run: |
        mkdir -p dhaf-${{ env.RELEASE_VERSION }}
        mkdir -p dhaf-${{ env.RELEASE_VERSION }}/libs
        mkdir -p dhaf-${{ env.RELEASE_VERSION }}/extensions/health-checkers/web
        mkdir -p dhaf-${{ env.RELEASE_VERSION }}/extensions/health-checkers/exec
        mkdir -p dhaf-${{ env.RELEASE_VERSION }}/extensions/health-checkers/tcp
        mkdir -p dhaf-${{ env.RELEASE_VERSION }}/extensions/switchers/cloudflare
        mkdir -p dhaf-${{ env.RELEASE_VERSION }}/extensions/switchers/google-cloud
        mkdir -p dhaf-${{ env.RELEASE_VERSION }}/extensions/switchers/exec
        mkdir -p dhaf-${{ env.RELEASE_VERSION }}/extensions/notifiers/email
        mkdir -p dhaf-${{ env.RELEASE_VERSION }}/extensions/notifiers/tg

        mv ./bin/win-x64/Dhaf.Node.exe dhaf-${{ env.RELEASE_VERSION }}/Dhaf.Node.exe
        mv ./bin/win-x64/Dhaf.CLI.exe dhaf-${{ env.RELEASE_VERSION }}/Dhaf.CLI.exe
        mv ./bin/win-x64/appsettings.json ./bin/win-x64/nlog.config dhaf-${{ env.RELEASE_VERSION }}
        mv ./bin/win-x64/core/* dhaf-${{ env.RELEASE_VERSION }}/libs

        mv ./bin/win-x64/ext/hc/web/* dhaf-${{ env.RELEASE_VERSION }}/extensions/health-checkers/web
        mv ./bin/win-x64/ext/hc/exec/* dhaf-${{ env.RELEASE_VERSION }}/extensions/health-checkers/exec
        mv ./bin/win-x64/ext/hc/tcp/* dhaf-${{ env.RELEASE_VERSION }}/extensions/health-checkers/tcp
        mv ./bin/win-x64/ext/sw/cloudflare/* dhaf-${{ env.RELEASE_VERSION }}/extensions/switchers/cloudflare
        mv ./bin/win-x64/ext/sw/google-cloud/* dhaf-${{ env.RELEASE_VERSION }}/extensions/switchers/google-cloud
        mv ./bin/win-x64/ext/sw/exec/* dhaf-${{ env.RELEASE_VERSION }}/extensions/switchers/exec
        mv ./bin/win-x64/ext/ntf/email/* dhaf-${{ env.RELEASE_VERSION }}/extensions/notifiers/email
        mv ./bin/win-x64/ext/ntf/tg/* dhaf-${{ env.RELEASE_VERSION }}/extensions/notifiers/tg

    - name: upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: dhaf-${{ env.RELEASE_VERSION }}
        path: dhaf-${{ env.RELEASE_VERSION }}
